maus: update regexes

diff --git a/bin/maus b/bin/maus
--- a/bin/maus
+++ b/bin/maus
@@ -6,16 +6,30 @@ echo "Writing to $OUTFILE ..."
 echo
 
 entry_url="http://www.wdrmaus.de/aktuelle-sendung/index.php5?startVideo=1"
-jsplayer_regex='http://deviceids-medp.wdr.de/ondemand.*\.js'
+jsplayer_regex='\(https\?\)\?://deviceids-medp.wdr.de/ondemand.*\.js'
 jsplayer_url=$(curl -L "$entry_url" 2>/dev/null | grep -om1 "$jsplayer_regex")
+case "$jsplayer_url" in
+	'//'*)      jsplayer_url="https:$jsplayer_url" ;;
+	'http://'*) ;;
+	'https://'*) ;;
+	*)          echo "Invalid jsplayer_url: $jsplayer_url"; exit 1;
+esac
 echo "Found JS player URL: $jsplayer_url"
 if [ -z "$jsplayer_url" ]; then
 	echo "Ooops. Extracting the JS player URL failed :("
 	exit
 fi
 
-video_regex='http://[^"]*\?\.\(m3u8\)'
+video_regex='\(https?:\)\?//[^"]*\?\.\(m3u8\)'
 video_url=$(curl -L "$jsplayer_url" 2>/dev/null | grep -om1 "$video_regex" | head -n 1)
+
+case "$video_url" in
+	'//'*)      video_url="https:$video_url" ;;
+	'http://'*) ;;
+	'https://'*) ;;
+	*)          echo "Invalid video_url: $video_url"; exit 1;
+esac
+
 echo "Found video URL: $video_url"
 if [ -z "$video_url" ]; then
 	echo "Ooops. Extracting the video URL failed :("
